export const rapport_ranking = [
    {
      "Rank": 1,
      "": "",
      "Player": "Shai Gilgeous-Alexander",
      "Age": 26,
      "Team(s)": "OKC",
      "Pos": "PG",
      "G": 49,
      "MP": "1,668",
      "Off": "+8.2",
      "Def": "+2.2",
      "Tot": "+10.5",
      "WAR": 12.4,
      "WAR/82": 20.4
    },
    {
      "Rank": 2,
      "": "",
      "Player": "Nikola Jokić",
      "Age": 29,
      "Team(s)": "DEN",
      "Pos": "C",
      "G": 46,
      "MP": "1,667",
      "Off": "+9.2",
      "Def": "+1.1",
      "Tot": "+10.3",
      "WAR": 12.1,
      "WAR/82": 19.1
    },
    {
      "Rank": 3,
      "": "",
      "Player": "Donovan Mitchell",
      "Age": 28,
      "Team(s)": "CLE",
      "Pos": "SG",
      "G": 49,
      "MP": "1,534",
      "Off": "+5.0",
      "Def": "+0.5",
      "Tot": "+5.5",
      "WAR": 7,
      "WAR/82": 11.1
    },
    {
      "Rank": 4,
      "": "",
      "Player": "Jayson Tatum",
      "Age": 26,
      "Team(s)": "BOS",
      "Pos": "PF",
      "G": 49,
      "MP": "1,780",
      "Off": "+3.5",
      "Def": "+1.0",
      "Tot": "+4.5",
      "WAR": 7,
      "WAR/82": 11.1
    },
    {
      "Rank": 5,
      "": "",
      "Player": "Giannis Antetokounmpo",
      "Age": 30,
      "Team(s)": "MIL",
      "Pos": "PF",
      "G": 41,
      "MP": "1,431",
      "Off": "+5.4",
      "Def": "+0.5",
      "Tot": "+5.9",
      "WAR": 6.9,
      "WAR/82": 11.3
    },
    {
      "Rank": 6,
      "": "",
      "Player": "Josh Hart",
      "Age": 29,
      "Team(s)": "NYK",
      "Pos": "SG",
      "G": 50,
      "MP": "1,879",
      "Off": "+2.3",
      "Def": "+1.2",
      "Tot": "+3.5",
      "WAR": 6.4,
      "WAR/82": 10.2
    },
    {
      "Rank": 7,
      "": "",
      "Player": "Anthony Edwards",
      "Age": 23,
      "Team(s)": "MIN",
      "Pos": "SG",
      "G": 51,
      "MP": "1,873",
      "Off": "+2.8",
      "Def": "+0.3",
      "Tot": "+3.1",
      "WAR": 5.9,
      "WAR/82": 9.3
    },
    {
      "Rank": 8,
      "": "",
      "Player": "Darius Garland",
      "Age": 25,
      "Team(s)": "CLE",
      "Pos": "PG",
      "G": 50,
      "MP": "1,517",
      "Off": "+5.2",
      "Def": "−1.1",
      "Tot": "+4.1",
      "WAR": 5.7,
      "WAR/82": 9
    },
    {
      "Rank": 9,
      "": "",
      "Player": "Karl-Anthony Towns",
      "Age": 29,
      "Team(s)": "NYK",
      "Pos": "C",
      "G": 46,
      "MP": "1,597",
      "Off": "+3.2",
      "Def": "+0.5",
      "Tot": "+3.7",
      "WAR": 5.6,
      "WAR/82": 9
    },
    {
      "Rank": 10,
      "": "",
      "Player": "Pascal Siakam",
      "Age": 30,
      "Team(s)": "IND",
      "Pos": "PF",
      "G": 50,
      "MP": "1,655",
      "Off": "+3.6",
      "Def": "−0.2",
      "Tot": "+3.4",
      "WAR": 5.6,
      "WAR/82": 9.2
    },
    {
      "Rank": 11,
      "": "",
      "Player": "Evan Mobley",
      "Age": 23,
      "Team(s)": "CLE",
      "Pos": "PF",
      "G": 46,
      "MP": "1,382",
      "Off": "+2.7",
      "Def": "+1.8",
      "Tot": "+4.6",
      "WAR": 5.6,
      "WAR/82": 8.8
    },
    {
      "Rank": 12,
      "": "",
      "Player": "Jalen Williams",
      "Age": 23,
      "Team(s)": "OKC",
      "Pos": "SG",
      "G": 47,
      "MP": "1,535",
      "Off": "+1.9",
      "Def": "+1.7",
      "Tot": "+3.7",
      "WAR": 5.4,
      "WAR/82": 8.8
    },
    {
      "Rank": 13,
      "": "",
      "Player": "Norman Powell",
      "Age": 31,
      "Team(s)": "LAC",
      "Pos": "SG",
      "G": 42,
      "MP": "1,397",
      "Off": "+3.8",
      "Def": "+0.5",
      "Tot": "+4.3",
      "WAR": 5.4,
      "WAR/82": 8.7
    },
    {
      "Rank": 14,
      "": "",
      "Player": "Amen Thompson",
      "Age": 22,
      "Team(s)": "HOU",
      "Pos": "SF",
      "G": 48,
      "MP": "1,509",
      "Off": "+1.3",
      "Def": "+2.5",
      "Tot": "+3.8",
      "WAR": 5.4,
      "WAR/82": 8.6
    },
    {
      "Rank": 15,
      "": "",
      "Player": "Jaren Jackson Jr.",
      "Age": 25,
      "Team(s)": "MEM",
      "Pos": "C",
      "G": 49,
      "MP": "1,452",
      "Off": "+2.5",
      "Def": "+1.5",
      "Tot": "+3.9",
      "WAR": 5.4,
      "WAR/82": 8.6
    },
    {
      "Rank": 16,
      "": "",
      "Player": "Tyrese Maxey",
      "Age": 24,
      "Team(s)": "PHI",
      "Pos": "PG",
      "G": 44,
      "MP": "1,673",
      "Off": "+3.6",
      "Def": "−0.5",
      "Tot": "+3.1",
      "WAR": 5.4,
      "WAR/82": 8.6
    },
    {
      "Rank": 17,
      "": "",
      "Player": "Jarrett Allen",
      "Age": 26,
      "Team(s)": "CLE",
      "Pos": "C",
      "G": 52,
      "MP": "1,504",
      "Off": "+2.1",
      "Def": "+1.5",
      "Tot": "+3.6",
      "WAR": 5.3,
      "WAR/82": 8.3
    },
    {
      "Rank": 18,
      "": "",
      "Player": "Tyrese Haliburton",
      "Age": 24,
      "Team(s)": "IND",
      "Pos": "PG",
      "G": 49,
      "MP": "1,668",
      "Off": "+3.5",
      "Def": "−0.4",
      "Tot": "+3.0",
      "WAR": 5.3,
      "WAR/82": 8.6
    },
    {
      "Rank": 19,
      "": "",
      "Player": "Franz Wagner",
      "Age": 23,
      "Team(s)": "ORL",
      "Pos": "SF",
      "G": 33,
      "MP": "1,082",
      "Off": "+4.5",
      "Def": "+1.5",
      "Tot": "+6.0",
      "WAR": 5.2,
      "WAR/82": 8.1
    },
    {
      "Rank": 20,
      "": "",
      "Player": "Jalen Brunson",
      "Age": 28,
      "Team(s)": "NYK",
      "Pos": "PG",
      "G": 50,
      "MP": "1,764",
      "Off": "+5.1",
      "Def": "−2.4",
      "Tot": "+2.7",
      "WAR": 5.2,
      "WAR/82": 8.4
    },
        {
          "Rank": 21,
          "": "",
          "Player": "Anthony Davis",
          "Age": 31,
          "Team(s)": "LAL",
          "Pos": "C",
          "G": 42,
          "MP": "1,440",
          "Off": "+2.4",
          "Def": "+1.4",
          "Tot": "+3.8",
          "WAR": 5.2,
          "WAR/82": 8.7
        },
        {
          "Rank": 22,
          "": "",
          "Player": "Derrick White",
          "Age": 30,
          "Team(s)": "BOS",
          "Pos": "SG",
          "G": 49,
          "MP": "1,647",
          "Off": "+2.1",
          "Def": "+0.8",
          "Tot": "+2.9",
          "WAR": 5.1,
          "WAR/82": 8
        },
        {
          "Rank": 23,
          "": "",
          "Player": "Kyrie Irving",
          "Age": 32,
          "Team(s)": "DAL",
          "Pos": "SG",
          "G": 41,
          "MP": "1,483",
          "Off": "+4.1",
          "Def": "−0.7",
          "Tot": "+3.5",
          "WAR": 5.1,
          "WAR/82": 8
        },
        {
          "Rank": 24,
          "": "",
          "Player": "Domantas Sabonis",
          "Age": 28,
          "Team(s)": "SAC",
          "Pos": "C",
          "G": 48,
          "MP": "1,727",
          "Off": "+3.1",
          "Def": "−0.5",
          "Tot": "+2.6",
          "WAR": 5,
          "WAR/82": 8
        },
        {
          "Rank": 25,
          "": "",
          "Player": "LeBron James",
          "Age": 40,
          "Team(s)": "LAL",
          "Pos": "SF",
          "G": 46,
          "MP": "1,595",
          "Off": "+3.9",
          "Def": "−0.9",
          "Tot": "+3.0",
          "WAR": 5,
          "WAR/82": 8.3
        },
        {
          "Rank": 26,
          "": "",
          "Player": "Devin Booker",
          "Age": 28,
          "Team(s)": "PHO",
          "Pos": "SG",
          "G": 46,
          "MP": "1,710",
          "Off": "+4.6",
          "Def": "−1.9",
          "Tot": "+2.6",
          "WAR": 5,
          "WAR/82": 8
        },
        {
          "Rank": 27,
          "": "",
          "Player": "Michael Porter Jr.",
          "Age": 26,
          "Team(s)": "DEN",
          "Pos": "SF",
          "G": 52,
          "MP": "1,730",
          "Off": "+2.9",
          "Def": "−0.4",
          "Tot": "+2.4",
          "WAR": 4.8,
          "WAR/82": 7.6
        },
        {
          "Rank": 28,
          "": "",
          "Player": "Damian Lillard",
          "Age": 34,
          "Team(s)": "MIL",
          "Pos": "PG",
          "G": 42,
          "MP": "1,523",
          "Off": "+4.0",
          "Def": "−1.0",
          "Tot": "+3.0",
          "WAR": 4.8,
          "WAR/82": 7.8
        },
        {
          "Rank": 29,
          "": "",
          "Player": "Victor Wembanyama",
          "Age": 21,
          "Team(s)": "SAS",
          "Pos": "C",
          "G": 43,
          "MP": "1,422",
          "Off": "+0.0",
          "Def": "+3.3",
          "Tot": "+3.3",
          "WAR": 4.7,
          "WAR/82": 7.9
        },
        {
          "Rank": 30,
          "": "",
          "Player": "Christian Braun",
          "Age": 23,
          "Team(s)": "DEN",
          "Pos": "SG",
          "G": 51,
          "MP": "1,664",
          "Off": "+2.0",
          "Def": "+0.5",
          "Tot": "+2.4",
          "WAR": 4.6,
          "WAR/82": 7.3
        },
        {
          "Rank": 31,
          "": "",
          "Player": "Jaylen Brown",
          "Age": 28,
          "Team(s)": "BOS",
          "Pos": "SF",
          "G": 45,
          "MP": "1,592",
          "Off": "+2.5",
          "Def": "+0.2",
          "Tot": "+2.6",
          "WAR": 4.6,
          "WAR/82": 7.3
        },
        {
          "Rank": 32,
          "": "",
          "Player": "Alperen Şengün",
          "Age": 22,
          "Team(s)": "HOU",
          "Pos": "C",
          "G": 48,
          "MP": "1,509",
          "Off": "+1.8",
          "Def": "+1.1",
          "Tot": "+2.8",
          "WAR": 4.6,
          "WAR/82": 7.3
        },
        {
          "Rank": 33,
          "": "",
          "Player": "Mikal Bridges",
          "Age": 28,
          "Team(s)": "NYK",
          "Pos": "SF",
          "G": 51,
          "MP": "1,955",
          "Off": "+1.9",
          "Def": "−0.3",
          "Tot": "+1.6",
          "WAR": 4.5,
          "WAR/82": 7.3
        },
        {
          "Rank": 34,
          "": "",
          "Player": "Payton Pritchard",
          "Age": 27,
          "Team(s)": "BOS",
          "Pos": "PG",
          "G": 51,
          "MP": "1,411",
          "Off": "+3.3",
          "Def": "−0.2",
          "Tot": "+3.2",
          "WAR": 4.5,
          "WAR/82": 7.1
        },
        {
          "Rank": 35,
          "": "",
          "Player": "Chris Paul",
          "Age": 39,
          "Team(s)": "SAS",
          "Pos": "PG",
          "G": 49,
          "MP": "1,424",
          "Off": "+2.1",
          "Def": "+0.9",
          "Tot": "+3.0",
          "WAR": 4.5,
          "WAR/82": 7.5
        },
        {
          "Rank": 36,
          "": "",
          "Player": "Dyson Daniels",
          "Age": 21,
          "Team(s)": "ATL",
          "Pos": "SG",
          "G": 47,
          "MP": "1,593",
          "Off": "−0.2",
          "Def": "+2.6",
          "Tot": "+2.4",
          "WAR": 4.4,
          "WAR/82": 7
        },
        {
          "Rank": 37,
          "": "",
          "Player": "Tyler Herro",
          "Age": 25,
          "Team(s)": "MIA",
          "Pos": "SG",
          "G": 49,
          "MP": "1,744",
          "Off": "+2.9",
          "Def": "−0.9",
          "Tot": "+2.0",
          "WAR": 4.4,
          "WAR/82": 7.2
        },
        {
          "Rank": 38,
          "": "",
          "Player": "Ivica Zubac",
          "Age": 27,
          "Team(s)": "LAC",
          "Pos": "C",
          "G": 49,
          "MP": "1,566",
          "Off": "+0.6",
          "Def": "+1.8",
          "Tot": "+2.4",
          "WAR": 4.3,
          "WAR/82": 7
        },
        {
          "Rank": 39,
          "": "",
          "Player": "DeMar DeRozan",
          "Age": 35,
          "Team(s)": "SAC",
          "Pos": "SF",
          "G": 46,
          "MP": "1,648",
          "Off": "+2.7",
          "Def": "−0.6",
          "Tot": "+2.1",
          "WAR": 4.3,
          "WAR/82": 6.9
        },
        {
          "Rank": 40,
          "": "",
          "Player": "Fred VanVleet",
          "Age": 30,
          "Team(s)": "HOU",
          "Pos": "PG",
          "G": 45,
          "MP": "1,596",
          "Off": "+0.7",
          "Def": "+1.5",
          "Tot": "+2.2",
          "WAR": 4.2,
          "WAR/82": 6.8
        }, 
        
            {
              "Rank": 41,
              "": "",
              "Player": "OG Anunoby",
              "Age": 27,
              "Team(s)": "NYK",
              "Pos": "PF",
              "G": 49,
              "MP": "1,778",
              "Off": "+0.9",
              "Def": "+0.8",
              "Tot": "+1.7",
              "WAR": 4.2,
              "WAR/82": 6.7
            },
            {
              "Rank": 42,
              "": "",
              "Player": "Austin Reaves",
              "Age": 26,
              "Team(s)": "LAL",
              "Pos": "SG",
              "G": 44,
              "MP": "1,525",
              "Off": "+2.6",
              "Def": "−0.3",
              "Tot": "+2.3",
              "WAR": 4.2,
              "WAR/82": 7
            },
            {
              "Rank": 43,
              "": "",
              "Player": "Ty Jerome",
              "Age": 27,
              "Team(s)": "CLE",
              "Pos": "SG",
              "G": 49,
              "MP": 932,
              "Off": "+4.8",
              "Def": "+0.5",
              "Tot": "+5.3",
              "WAR": 4.2,
              "WAR/82": 6.6
            },
            {
              "Rank": 44,
              "": "",
              "Player": "Desmond Bane",
              "Age": 26,
              "Team(s)": "MEM",
              "Pos": "SG",
              "G": 40,
              "MP": "1,203",
              "Off": "+2.9",
              "Def": "+0.6",
              "Tot": "+3.5",
              "WAR": 4.1,
              "WAR/82": 6.6
            },
            {
              "Rank": 45,
              "": "",
              "Player": "Zach LaVine",
              "Age": 29,
              "Team(s)": "CHI, SAC",
              "Pos": "SF, SG",
              "G": 44,
              "MP": "1,499",
              "Off": "+3.1",
              "Def": "−0.9",
              "Tot": "+2.2",
              "WAR": 4,
              "WAR/82": 6.3
            },
            {
              "Rank": 46,
              "": "",
              "Player": "Luka Dončić",
              "Age": 25,
              "Team(s)": "DAL",
              "Pos": "PG",
              "G": 22,
              "MP": 785,
              "Off": "+4.6",
              "Def": "+1.7",
              "Tot": "+6.3",
              "WAR": 3.9,
              "WAR/82": 6.2
            },
            {
              "Rank": 47,
              "": "",
              "Player": "De'Aaron Fox",
              "Age": 27,
              "Team(s)": "SAC, SAS",
              "Pos": "PG",
              "G": 47,
              "MP": "1,733",
              "Off": "+2.1",
              "Def": "−0.7",
              "Tot": "+1.4",
              "WAR": 3.8,
              "WAR/82": 6.2
            },
            {
              "Rank": 48,
              "": "",
              "Player": "James Harden",
              "Age": 35,
              "Team(s)": "LAC",
              "Pos": "PG",
              "G": 48,
              "MP": "1,627",
              "Off": "+0.6",
              "Def": "+1.0",
              "Tot": "+1.6",
              "WAR": 3.8,
              "WAR/82": 6.1
            },
            {
              "Rank": 49,
              "": "",
              "Player": "Nikola Vučević",
              "Age": 34,
              "Team(s)": "CHI",
              "Pos": "C",
              "G": 51,
              "MP": "1,645",
              "Off": "+1.8",
              "Def": "−0.4",
              "Tot": "+1.4",
              "WAR": 3.6,
              "WAR/82": 5.7
            },
            {
              "Rank": 50,
              "": "",
              "Player": "Kevin Durant",
              "Age": 36,
              "Team(s)": "PHO",
              "Pos": "PF",
              "G": 39,
              "MP": "1,410",
              "Off": "+2.9",
              "Def": "−0.9",
              "Tot": "+2.0",
              "WAR": 3.6,
              "WAR/82": 5.7
            },
            {
              "Rank": 51,
              "": "",
              "Player": "Cade Cunningham",
              "Age": 23,
              "Team(s)": "DET",
              "Pos": "PG",
              "G": 47,
              "MP": "1,677",
              "Off": "+1.7",
              "Def": "−0.4",
              "Tot": "+1.3",
              "WAR": 3.6,
              "WAR/82": 5.6
            },
            {
              "Rank": 52,
              "": "",
              "Player": "Tari Eason",
              "Age": 23,
              "Team(s)": "HOU",
              "Pos": "PF",
              "G": 34,
              "MP": 806,
              "Off": "+1.0",
              "Def": "+4.3",
              "Tot": "+5.2",
              "WAR": 3.5,
              "WAR/82": 5.7
            },
            {
              "Rank": 53,
              "": "",
              "Player": "Stephen Curry",
              "Age": 36,
              "Team(s)": "GSW",
              "Pos": "PG",
              "G": 42,
              "MP": "1,343",
              "Off": "+2.5",
              "Def": "−0.5",
              "Tot": "+2.0",
              "WAR": 3.4,
              "WAR/82": 5.5
            },
            {
              "Rank": 54,
              "": "",
              "Player": "Jalen Johnson",
              "Age": 23,
              "Team(s)": "ATL",
              "Pos": "SF",
              "G": 36,
              "MP": "1,284",
              "Off": "+0.3",
              "Def": "+1.9",
              "Tot": "+2.2",
              "WAR": 3.4,
              "WAR/82": 5.4
            },
            {
              "Rank": 55,
              "": "",
              "Player": "Jamal Murray",
              "Age": 27,
              "Team(s)": "DEN",
              "Pos": "PG",
              "G": 45,
              "MP": "1,619",
              "Off": "+1.5",
              "Def": "−0.3",
              "Tot": "+1.2",
              "WAR": 3.4,
              "WAR/82": 5.3
            },
            {
              "Rank": 56,
              "": "",
              "Player": "Malik Beasley",
              "Age": 28,
              "Team(s)": "DET",
              "Pos": "SG",
              "G": 52,
              "MP": "1,452",
              "Off": "+2.2",
              "Def": "−0.6",
              "Tot": "+1.5",
              "WAR": 3.3,
              "WAR/82": 5.2
            },
            {
              "Rank": 57,
              "": "",
              "Player": "Luguentz Dort",
              "Age": 25,
              "Team(s)": "OKC",
              "Pos": "SF",
              "G": 47,
              "MP": "1,362",
              "Off": "−0.3",
              "Def": "+2.1",
              "Tot": "+1.8",
              "WAR": 3.3,
              "WAR/82": 5.4
            },
            {
              "Rank": 58,
              "": "",
              "Player": "Cason Wallace",
              "Age": 21,
              "Team(s)": "OKC",
              "Pos": "SG",
              "G": 46,
              "MP": "1,259",
              "Off": "−1.1",
              "Def": "+3.1",
              "Tot": "+2.0",
              "WAR": 3.2,
              "WAR/82": 5.3
            },
            {
              "Rank": 59,
              "": "",
              "Player": "Santi Aldama",
              "Age": 24,
              "Team(s)": "MEM",
              "Pos": "PF",
              "G": 43,
              "MP": "1,057",
              "Off": "+1.7",
              "Def": "+1.2",
              "Tot": "+2.9",
              "WAR": 3.2,
              "WAR/82": 5.2
            },
            {
              "Rank": 60,
              "": "",
              "Player": "Derrick Jones Jr.",
              "Age": 27,
              "Team(s)": "LAC",
              "Pos": "SF",
              "G": 49,
              "MP": "1,235",
              "Off": "+0.4",
              "Def": "+1.7",
              "Tot": "+2.1",
              "WAR": 3.2,
              "WAR/82": 5.2
            },
            
                {
                  "Rank": 61,
                  "": "",
                  "Player": "Keon Ellis",
                  "Age": 25,
                  "Team(s)": "SAC",
                  "Pos": "SG",
                  "G": 49,
                  "MP": "1,072",
                  "Off": "+0.5",
                  "Def": "+2.3",
                  "Tot": "+2.8",
                  "WAR": 3.2,
                  "WAR/82": 5.2
                },
                {
                  "Rank": 62,
                  "": "",
                  "Player": "Malik Monk",
                  "Age": 26,
                  "Team(s)": "SAC",
                  "Pos": "SG",
                  "G": 43,
                  "MP": "1,379",
                  "Off": "+1.9",
                  "Def": "−0.3",
                  "Tot": "+1.6",
                  "WAR": 3.1,
                  "WAR/82": 5.1
                },
                {
                  "Rank": 63,
                  "": "",
                  "Player": "Jimmy Butler",
                  "Age": 35,
                  "Team(s)": "MIA",
                  "Pos": "PF",
                  "G": 25,
                  "MP": 766,
                  "Off": "+4.9",
                  "Def": "−0.2",
                  "Tot": "+4.8",
                  "WAR": 3.1,
                  "WAR/82": 5.2
                },
                {
                  "Rank": 64,
                  "": "",
                  "Player": "Trey Murphy III",
                  "Age": 24,
                  "Team(s)": "NOP",
                  "Pos": "SF",
                  "G": 35,
                  "MP": "1,237",
                  "Off": "+3.3",
                  "Def": "−1.5",
                  "Tot": "+1.8",
                  "WAR": 3.1,
                  "WAR/82": 4.9
                },
                {
                  "Rank": 65,
                  "": "",
                  "Player": "Brandon Clarke",
                  "Age": 28,
                  "Team(s)": "MEM",
                  "Pos": "PF",
                  "G": 47,
                  "MP": 885,
                  "Off": "+1.3",
                  "Def": "+2.0",
                  "Tot": "+3.3",
                  "WAR": 2.9,
                  "WAR/82": 4.7
                },
                {
                  "Rank": 66,
                  "": "",
                  "Player": "Isaiah Joe",
                  "Age": 25,
                  "Team(s)": "OKC",
                  "Pos": "SG",
                  "G": 46,
                  "MP": 970,
                  "Off": "+1.5",
                  "Def": "+1.2",
                  "Tot": "+2.7",
                  "WAR": 2.9,
                  "WAR/82": 4.7
                },
                {
                  "Rank": 67,
                  "": "",
                  "Player": "Daniel Gafford",
                  "Age": 26,
                  "Team(s)": "DAL",
                  "Pos": "C",
                  "G": 49,
                  "MP": "1,079",
                  "Off": "+2.2",
                  "Def": "−0.0",
                  "Tot": "+2.1",
                  "WAR": 2.8,
                  "WAR/82": 4.5
                },
                {
                  "Rank": 68,
                  "": "",
                  "Player": "Rudy Gobert",
                  "Age": 32,
                  "Team(s)": "MIN",
                  "Pos": "C",
                  "G": 52,
                  "MP": "1,730",
                  "Off": "−1.0",
                  "Def": "+1.3",
                  "Tot": "+0.4",
                  "WAR": 2.8,
                  "WAR/82": 4.4
                },
                {
                  "Rank": 69,
                  "": "",
                  "Player": "John Collins",
                  "Age": 27,
                  "Team(s)": "UTA",
                  "Pos": "PF",
                  "G": 33,
                  "MP": 996,
                  "Off": "+1.7",
                  "Def": "+0.7",
                  "Tot": "+2.4",
                  "WAR": 2.7,
                  "WAR/82": 4.5
                },
                {
                  "Rank": 70,
                  "": "",
                  "Player": "Cameron Johnson",
                  "Age": 28,
                  "Team(s)": "BRK",
                  "Pos": "PF",
                  "G": 37,
                  "MP": "1,185",
                  "Off": "+2.8",
                  "Def": "−1.2",
                  "Tot": "+1.6",
                  "WAR": 2.7,
                  "WAR/82": 4.3
                },
                {
                  "Rank": 71,
                  "": "",
                  "Player": "Luke Kennard",
                  "Age": 28,
                  "Team(s)": "MEM",
                  "Pos": "SG",
                  "G": 38,
                  "MP": 842,
                  "Off": "+3.1",
                  "Def": "+0.1",
                  "Tot": "+3.2",
                  "WAR": 2.7,
                  "WAR/82": 4.4
                },
                {
                  "Rank": 72,
                  "": "",
                  "Player": "Aaron Wiggins",
                  "Age": 26,
                  "Team(s)": "OKC",
                  "Pos": "SG",
                  "G": 50,
                  "MP": "1,081",
                  "Off": "+1.1",
                  "Def": "+0.9",
                  "Tot": "+2.0",
                  "WAR": 2.7,
                  "WAR/82": 4.5
                },
                {
                  "Rank": 73,
                  "": "",
                  "Player": "Goga Bitadze",
                  "Age": 25,
                  "Team(s)": "ORL",
                  "Pos": "C",
                  "G": 42,
                  "MP": "1,002",
                  "Off": "−0.5",
                  "Def": "+2.8",
                  "Tot": "+2.3",
                  "WAR": 2.7,
                  "WAR/82": 4.2
                },
                {
                  "Rank": 74,
                  "": "",
                  "Player": "Mike Conley",
                  "Age": 37,
                  "Team(s)": "MIN",
                  "Pos": "PG",
                  "G": 47,
                  "MP": "1,179",
                  "Off": "+0.4",
                  "Def": "+1.2",
                  "Tot": "+1.6",
                  "WAR": 2.7,
                  "WAR/82": 4.3
                },
                {
                  "Rank": 75,
                  "": "",
                  "Player": "Tobias Harris",
                  "Age": 32,
                  "Team(s)": "DET",
                  "Pos": "PF",
                  "G": 50,
                  "MP": "1,600",
                  "Off": "−0.6",
                  "Def": "+1.1",
                  "Tot": "+0.5",
                  "WAR": 2.7,
                  "WAR/82": 4.3
                },
                {
                  "Rank": 76,
                  "": "",
                  "Player": "Naz Reid",
                  "Age": 25,
                  "Team(s)": "MIN",
                  "Pos": "C",
                  "G": 51,
                  "MP": "1,324",
                  "Off": "+0.5",
                  "Def": "+0.6",
                  "Tot": "+1.1",
                  "WAR": 2.7,
                  "WAR/82": 4.3
                },
                {
                  "Rank": 77,
                  "": "",
                  "Player": "Scottie Barnes",
                  "Age": 23,
                  "Team(s)": "TOR",
                  "Pos": "PF",
                  "G": 39,
                  "MP": "1,344",
                  "Off": "+0.4",
                  "Def": "+0.7",
                  "Tot": "+1.1",
                  "WAR": 2.7,
                  "WAR/82": 4.3
                },
                {
                  "Rank": 78,
                  "": "",
                  "Player": "LaMelo Ball",
                  "Age": 23,
                  "Team(s)": "CHO",
                  "Pos": "PG",
                  "G": 32,
                  "MP": "1,068",
                  "Off": "+2.7",
                  "Def": "−0.8",
                  "Tot": "+1.9",
                  "WAR": 2.7,
                  "WAR/82": 4.5
                },
                {
                  "Rank": 79,
                  "": "",
                  "Player": "Jaden McDaniels",
                  "Age": 24,
                  "Team(s)": "MIN",
                  "Pos": "PF",
                  "G": 52,
                  "MP": "1,635",
                  "Off": "−1.4",
                  "Def": "+1.8",
                  "Tot": "+0.4",
                  "WAR": 2.7,
                  "WAR/82": 4.2
                },
                {
                  "Rank": 80,
                  "": "",
                  "Player": "Jakob Poeltl",
                  "Age": 29,
                  "Team(s)": "TOR",
                  "Pos": "C",
                  "G": 45,
                  "MP": "1,389",
                  "Off": "+0.1",
                  "Def": "+0.8",
                  "Tot": "+0.9",
                  "WAR": 2.7,
                  "WAR/82": 4.2
                },
                
                    {
                      "Rank": 81,
                      "": "",
                      "Player": "Andrew Wiggins",
                      "Age": 29,
                      "Team(s)": "GSW",
                      "Pos": "SF",
                      "G": 43,
                      "MP": "1,296",
                      "Off": "+1.3",
                      "Def": "−0.2",
                      "Tot": "+1.1",
                      "WAR": 2.6,
                      "WAR/82": 4.2
                    },
                    {
                      "Rank": 82,
                      "": "",
                      "Player": "Trae Young",
                      "Age": 26,
                      "Team(s)": "ATL",
                      "Pos": "PG",
                      "G": 48,
                      "MP": "1,731",
                      "Off": "+1.8",
                      "Def": "−1.7",
                      "Tot": "+0.2",
                      "WAR": 2.6,
                      "WAR/82": 4.1
                    },
                    {
                      "Rank": 83,
                      "": "",
                      "Player": "Deni Avdija",
                      "Age": 24,
                      "Team(s)": "POR",
                      "Pos": "SF",
                      "G": 49,
                      "MP": "1,405",
                      "Off": "+0.3",
                      "Def": "+0.4",
                      "Tot": "+0.7",
                      "WAR": 2.6,
                      "WAR/82": 4.1
                    },
                    {
                      "Rank": 84,
                      "": "",
                      "Player": "Kentavious Caldwell-Pope",
                      "Age": 31,
                      "Team(s)": "ORL",
                      "Pos": "SG",
                      "G": 50,
                      "MP": "1,522",
                      "Off": "−1.3",
                      "Def": "+1.8",
                      "Tot": "+0.5",
                      "WAR": 2.6,
                      "WAR/82": 4
                    },
                    {
                      "Rank": 85,
                      "": "",
                      "Player": "Julius Randle",
                      "Age": 30,
                      "Team(s)": "MIN",
                      "Pos": "PF",
                      "G": 48,
                      "MP": "1,564",
                      "Off": "+1.1",
                      "Def": "−0.7",
                      "Tot": "+0.4",
                      "WAR": 2.5,
                      "WAR/82": 4
                    },
                    {
                      "Rank": 86,
                      "": "",
                      "Player": "Alex Caruso",
                      "Age": 30,
                      "Team(s)": "OKC",
                      "Pos": "SG",
                      "G": 30,
                      "MP": 571,
                      "Off": "−0.2",
                      "Def": "+5.5",
                      "Tot": "+5.3",
                      "WAR": 2.5,
                      "WAR/82": 4.2
                    },
                    {
                      "Rank": 87,
                      "": "",
                      "Player": "Collin Sexton",
                      "Age": 26,
                      "Team(s)": "UTA",
                      "Pos": "SG",
                      "G": 46,
                      "MP": "1,313",
                      "Off": "+3.1",
                      "Def": "−2.3",
                      "Tot": "+0.8",
                      "WAR": 2.5,
                      "WAR/82": 4.1
                    },
                    {
                      "Rank": 88,
                      "": "",
                      "Player": "Luke Kornet",
                      "Age": 29,
                      "Team(s)": "BOS",
                      "Pos": "C",
                      "G": 46,
                      "MP": 779,
                      "Off": "+1.3",
                      "Def": "+1.8",
                      "Tot": "+3.1",
                      "WAR": 2.5,
                      "WAR/82": 3.9
                    },
                    {
                      "Rank": 89,
                      "": "",
                      "Player": "Caris LeVert",
                      "Age": 30,
                      "Team(s)": "CLE",
                      "Pos": "SF",
                      "G": 38,
                      "MP": 904,
                      "Off": "+1.4",
                      "Def": "+0.8",
                      "Tot": "+2.3",
                      "WAR": 2.5,
                      "WAR/82": 3.9
                    },
                    {
                      "Rank": 90,
                      "": "",
                      "Player": "Ja Morant",
                      "Age": 25,
                      "Team(s)": "MEM",
                      "Pos": "PG",
                      "G": 30,
                      "MP": 851,
                      "Off": "+2.2",
                      "Def": "+0.3",
                      "Tot": "+2.6",
                      "WAR": 2.5,
                      "WAR/82": 3.9
                    },
                    {
                      "Rank": 91,
                      "": "",
                      "Player": "Kelly Oubre Jr.",
                      "Age": 29,
                      "Team(s)": "PHI",
                      "Pos": "SF",
                      "G": 48,
                      "MP": "1,656",
                      "Off": "−0.5",
                      "Def": "+0.7",
                      "Tot": "+0.1",
                      "WAR": 2.4,
                      "WAR/82": 3.9
                    },
                    {
                      "Rank": 92,
                      "": "",
                      "Player": "P.J. Washington",
                      "Age": 26,
                      "Team(s)": "DAL",
                      "Pos": "PF",
                      "G": 42,
                      "MP": "1,383",
                      "Off": "−1.1",
                      "Def": "+1.6",
                      "Tot": "+0.6",
                      "WAR": 2.4,
                      "WAR/82": 3.8
                    },
                    {
                      "Rank": 93,
                      "": "",
                      "Player": "Klay Thompson",
                      "Age": 34,
                      "Team(s)": "DAL",
                      "Pos": "SF",
                      "G": 45,
                      "MP": "1,228",
                      "Off": "+0.7",
                      "Def": "+0.0",
                      "Tot": "+0.8",
                      "WAR": 2.3,
                      "WAR/82": 3.6
                    },
                    {
                      "Rank": 94,
                      "": "",
                      "Player": "Walker Kessler",
                      "Age": 23,
                      "Team(s)": "UTA",
                      "Pos": "C",
                      "G": 40,
                      "MP": "1,209",
                      "Off": "−0.0",
                      "Def": "+0.8",
                      "Tot": "+0.8",
                      "WAR": 2.3,
                      "WAR/82": 3.7
                    },
                    {
                      "Rank": 95,
                      "": "",
                      "Player": "Bam Adebayo",
                      "Age": 27,
                      "Team(s)": "MIA",
                      "Pos": "C",
                      "G": 49,
                      "MP": "1,664",
                      "Off": "−1.0",
                      "Def": "+0.9",
                      "Tot": "−0.1",
                      "WAR": 2.2,
                      "WAR/82": 3.6
                    },
                    {
                      "Rank": 96,
                      "": "",
                      "Player": "RJ Barrett",
                      "Age": 24,
                      "Team(s)": "TOR",
                      "Pos": "SF",
                      "G": 41,
                      "MP": "1,365",
                      "Off": "+1.2",
                      "Def": "−0.8",
                      "Tot": "+0.4",
                      "WAR": 2.2,
                      "WAR/82": 3.5
                    },
                    {
                      "Rank": 97,
                      "": "",
                      "Player": "Jake LaRavia",
                      "Age": 23,
                      "Team(s)": "MEM",
                      "Pos": "PF",
                      "G": 47,
                      "MP": 982,
                      "Off": "+0.1",
                      "Def": "+1.4",
                      "Tot": "+1.4",
                      "WAR": 2.2,
                      "WAR/82": 3.5
                    },
                    {
                      "Rank": 98,
                      "": "",
                      "Player": "Isaiah Hartenstein",
                      "Age": 26,
                      "Team(s)": "OKC",
                      "Pos": "C",
                      "G": 30,
                      "MP": 875,
                      "Off": "−1.0",
                      "Def": "+2.8",
                      "Tot": "+1.8",
                      "WAR": 2.2,
                      "WAR/82": 3.5
                    },
                    {
                      "Rank": 99,
                      "": "",
                      "Player": "Kristaps Porziņģis",
                      "Age": 29,
                      "Team(s)": "BOS",
                      "Pos": "C",
                      "G": 27,
                      "MP": 771,
                      "Off": "+2.3",
                      "Def": "+0.2",
                      "Tot": "+2.4",
                      "WAR": 2.1,
                      "WAR/82": 3.4
                    },
                    {
                      "Rank": 100,
                      "": "",
                      "Player": "Andrew Nembhard",
                      "Age": 25,
                      "Team(s)": "IND",
                      "Pos": "SG",
                      "G": 34,
                      "MP": 970,
                      "Off": "+0.7",
                      "Def": "+0.7",
                      "Tot": "+1.4",
                      "WAR": 2.1,
                      "WAR/82": 3.5
                    }, 

        
                        {
                          "Rank": 101,
                          "": "",
                          "Player": "Dereck Lively II",
                          "Age": 20,
                          "Team(s)": "DAL",
                          "Pos": "C",
                          "G": 32,
                          "MP": 768,
                          "Off": "+1.1",
                          "Def": "+1.3",
                          "Tot": "+2.3",
                          "WAR": 2.1,
                          "WAR/82": 3.3
                        },
                        {
                          "Rank": 102,
                          "": "",
                          "Player": "Scotty Pippen Jr.",
                          "Age": 24,
                          "Team(s)": "MEM",
                          "Pos": "PG",
                          "G": 51,
                          "MP": "1,081",
                          "Off": "+0.1",
                          "Def": "+0.8",
                          "Tot": "+0.9",
                          "WAR": 2.1,
                          "WAR/82": 3.4
                        },
                        {
                          "Rank": 103,
                          "": "",
                          "Player": "Anfernee Simons",
                          "Age": 25,
                          "Team(s)": "POR",
                          "Pos": "SG",
                          "G": 48,
                          "MP": "1,549",
                          "Off": "+1.8",
                          "Def": "−1.9",
                          "Tot": "−0.1",
                          "WAR": 2.1,
                          "WAR/82": 3.3
                        },
                        {
                          "Rank": 104,
                          "": "",
                          "Player": "Donte DiVincenzo",
                          "Age": 28,
                          "Team(s)": "MIN",
                          "Pos": "SG",
                          "G": 40,
                          "MP": "1,057",
                          "Off": "−0.0",
                          "Def": "+1.0",
                          "Tot": "+0.9",
                          "WAR": 2.1,
                          "WAR/82": 3.2
                        },
                        {
                          "Rank": 105,
                          "": "",
                          "Player": "T.J. McConnell",
                          "Age": 32,
                          "Team(s)": "IND",
                          "Pos": "PG",
                          "G": 49,
                          "MP": 912,
                          "Off": "+1.1",
                          "Def": "+0.3",
                          "Tot": "+1.5",
                          "WAR": 2,
                          "WAR/82": 3.3
                        },
                        {
                          "Rank": 106,
                          "": "",
                          "Player": "Grayson Allen",
                          "Age": 29,
                          "Team(s)": "PHO",
                          "Pos": "SG",
                          "G": 42,
                          "MP": "1,054",
                          "Off": "+1.3",
                          "Def": "−0.4",
                          "Tot": "+0.9",
                          "WAR": 2,
                          "WAR/82": 3.3
                        },
                        {
                          "Rank": 107,
                          "": "",
                          "Player": "Jalen Duren",
                          "Age": 21,
                          "Team(s)": "DET",
                          "Pos": "C",
                          "G": 49,
                          "MP": "1,253",
                          "Off": "−0.2",
                          "Def": "+0.5",
                          "Tot": "+0.3",
                          "WAR": 2,
                          "WAR/82": 3.1
                        },
                        {
                          "Rank": 108,
                          "": "",
                          "Player": "Bobby Portis",
                          "Age": 29,
                          "Team(s)": "MIL",
                          "Pos": "PF",
                          "G": 43,
                          "MP": "1,081",
                          "Off": "−0.2",
                          "Def": "+0.9",
                          "Tot": "+0.7",
                          "WAR": 2,
                          "WAR/82": 3.2
                        },
                        {
                          "Rank": 109,
                          "": "",
                          "Player": "Miles Bridges",
                          "Age": 26,
                          "Team(s)": "CHO",
                          "Pos": "PF",
                          "G": 35,
                          "MP": "1,120",
                          "Off": "+0.7",
                          "Def": "−0.0",
                          "Tot": "+0.6",
                          "WAR": 2,
                          "WAR/82": 3.3
                        },
                        {
                          "Rank": 110,
                          "": "",
                          "Player": "Rui Hachimura",
                          "Age": 26,
                          "Team(s)": "LAL",
                          "Pos": "PF",
                          "G": 42,
                          "MP": "1,346",
                          "Off": "+0.1",
                          "Def": "−0.1",
                          "Tot": "+0.1",
                          "WAR": 2,
                          "WAR/82": 3.3
                        },
                        {
                          "Rank": 111,
                          "": "",
                          "Player": "Dillon Brooks",
                          "Age": 29,
                          "Team(s)": "HOU",
                          "Pos": "SF",
                          "G": 48,
                          "MP": "1,551",
                          "Off": "−0.3",
                          "Def": "+0.0",
                          "Tot": "−0.3",
                          "WAR": 1.9,
                          "WAR/82": 3.1
                        },
                        {
                          "Rank": 112,
                          "": "",
                          "Player": "Toumani Camara",
                          "Age": 24,
                          "Team(s)": "POR",
                          "Pos": "PF",
                          "G": 50,
                          "MP": "1,611",
                          "Off": "−1.0",
                          "Def": "+0.6",
                          "Tot": "−0.4",
                          "WAR": 1.9,
                          "WAR/82": 3
                        },
                        {
                          "Rank": 113,
                          "": "",
                          "Player": "Brandin Podziemski",
                          "Age": 21,
                          "Team(s)": "GSW",
                          "Pos": "SG",
                          "G": 38,
                          "MP": 938,
                          "Off": "+0.0",
                          "Def": "+1.0",
                          "Tot": "+1.0",
                          "WAR": 1.9,
                          "WAR/82": 3
                        },
                        {
                          "Rank": 114,
                          "": "",
                          "Player": "Ausar Thompson",
                          "Age": 22,
                          "Team(s)": "DET",
                          "Pos": "SF",
                          "G": 30,
                          "MP": 618,
                          "Off": "−0.2",
                          "Def": "+3.1",
                          "Tot": "+2.9",
                          "WAR": 1.9,
                          "WAR/82": 3
                        },
                        {
                          "Rank": 115,
                          "": "",
                          "Player": "Sam Hauser",
                          "Age": 27,
                          "Team(s)": "BOS",
                          "Pos": "PF",
                          "G": 43,
                          "MP": 855,
                          "Off": "+0.8",
                          "Def": "+0.7",
                          "Tot": "+1.4",
                          "WAR": 1.9,
                          "WAR/82": 3
                        },
                        {
                          "Rank": 116,
                          "": "",
                          "Player": "Jrue Holiday",
                          "Age": 34,
                          "Team(s)": "BOS",
                          "Pos": "PG",
                          "G": 44,
                          "MP": "1,330",
                          "Off": "−0.4",
                          "Def": "+0.4",
                          "Tot": "−0.0",
                          "WAR": 1.9,
                          "WAR/82": 2.9
                        },
                        {
                          "Rank": 117,
                          "": "",
                          "Player": "Lauri Markkanen",
                          "Age": 27,
                          "Team(s)": "UTA",
                          "Pos": "PF",
                          "G": 38,
                          "MP": "1,219",
                          "Off": "+1.8",
                          "Def": "−1.6",
                          "Tot": "+0.2",
                          "WAR": 1.8,
                          "WAR/82": 3
                        },
                        {
                          "Rank": 118,
                          "": "",
                          "Player": "Cody Martin",
                          "Age": 29,
                          "Team(s)": "CHO",
                          "Pos": "SF",
                          "G": 39,
                          "MP": 967,
                          "Off": "−1.1",
                          "Def": "+2.0",
                          "Tot": "+0.9",
                          "WAR": 1.8,
                          "WAR/82": 3.1
                        },
                        {
                          "Rank": 119,
                          "": "",
                          "Player": "Royce O'Neale",
                          "Age": 31,
                          "Team(s)": "PHO",
                          "Pos": "SF",
                          "G": 45,
                          "MP": "1,141",
                          "Off": "−0.3",
                          "Def": "+0.7",
                          "Tot": "+0.4",
                          "WAR": 1.8,
                          "WAR/82": 3
                        },
                        {
                          "Rank": 120,
                          "": "",
                          "Player": "Jalen Green",
                          "Age": 22,
                          "Team(s)": "HOU",
                          "Pos": "SG",
                          "G": 51,
                          "MP": "1,693",
                          "Off": "+0.3",
                          "Def": "−0.9",
                          "Tot": "−0.6",
                          "WAR": 1.8,
                          "WAR/82": 3
                        },
                        
                            {
                              "Rank": 121,
                              "": "",
                              "Player": "Nickeil Alexander-Walker",
                              "Age": 26,
                              "Team(s)": "MIN",
                              "Pos": "SG",
                              "G": 52,
                              "MP": "1,242",
                              "Off": "−0.5",
                              "Def": "+0.5",
                              "Tot": "+0.1",
                              "WAR": 1.8,
                              "WAR/82": 2.8
                            },
                            {
                              "Rank": 122,
                              "": "",
                              "Player": "Khris Middleton",
                              "Age": 33,
                              "Team(s)": "MIL",
                              "Pos": "SF",
                              "G": 23,
                              "MP": 534,
                              "Off": "+2.9",
                              "Def": "+0.3",
                              "Tot": "+3.2",
                              "WAR": 1.7,
                              "WAR/82": 2.9
                            },
                            {
                              "Rank": 123,
                              "": "",
                              "Player": "Chris Boucher",
                              "Age": 32,
                              "Team(s)": "TOR",
                              "Pos": "PF",
                              "G": 44,
                              "MP": 763,
                              "Off": "+1.8",
                              "Def": "−0.4",
                              "Tot": "+1.5",
                              "WAR": 1.7,
                              "WAR/82": 2.7
                            },
                            {
                              "Rank": 124,
                              "": "",
                              "Player": "Josh Okogie",
                              "Age": 26,
                              "Team(s)": "CHO, PHO",
                              "Pos": "SG",
                              "G": 32,
                              "MP": 500,
                              "Off": "+0.7",
                              "Def": "+2.8",
                              "Tot": "+3.5",
                              "WAR": 1.7,
                              "WAR/82": 2.8
                            },
                            {
                              "Rank": 125,
                              "": "",
                              "Player": "Dorian Finney-Smith",
                              "Age": 31,
                              "Team(s)": "BRK, LAL",
                              "Pos": "PF",
                              "G": 35,
                              "MP": 946,
                              "Off": "−0.3",
                              "Def": "+1.0",
                              "Tot": "+0.7",
                              "WAR": 1.7,
                              "WAR/82": 2.7
                            },
                            {
                              "Rank": 126,
                              "": "",
                              "Player": "Paul George",
                              "Age": 34,
                              "Team(s)": "PHI",
                              "Pos": "PF",
                              "G": 32,
                              "MP": "1,023",
                              "Off": "−0.2",
                              "Def": "+0.6",
                              "Tot": "+0.4",
                              "WAR": 1.6,
                              "WAR/82": 2.6
                            },
                            {
                              "Rank": 127,
                              "": "",
                              "Player": "Cameron Payne",
                              "Age": 30,
                              "Team(s)": "NYK",
                              "Pos": "PG",
                              "G": 45,
                              "MP": 642,
                              "Off": "+1.8",
                              "Def": "+0.2",
                              "Tot": "+2.0",
                              "WAR": 1.6,
                              "WAR/82": 2.6
                            },
                            {
                              "Rank": 128,
                              "": "",
                              "Player": "Russell Westbrook",
                              "Age": 36,
                              "Team(s)": "DEN",
                              "Pos": "PG",
                              "G": 48,
                              "MP": "1,328",
                              "Off": "−0.5",
                              "Def": "+0.2",
                              "Tot": "−0.3",
                              "WAR": 1.6,
                              "WAR/82": 2.6
                            },
                            {
                              "Rank": 129,
                              "": "",
                              "Player": "Naji Marshall",
                              "Age": 27,
                              "Team(s)": "DAL",
                              "Pos": "SF",
                              "G": 39,
                              "MP": 954,
                              "Off": "+1.0",
                              "Def": "−0.5",
                              "Tot": "+0.5",
                              "WAR": 1.6,
                              "WAR/82": 2.5
                            },
                            {
                              "Rank": 130,
                              "": "",
                              "Player": "Jaylen Wells",
                              "Age": 21,
                              "Team(s)": "MEM",
                              "Pos": "SG",
                              "G": 51,
                              "MP": "1,331",
                              "Off": "+0.4",
                              "Def": "−0.7",
                              "Tot": "−0.4",
                              "WAR": 1.6,
                              "WAR/82": 2.6
                            },
                            {
                              "Rank": 131,
                              "": "",
                              "Player": "Zach Edey",
                              "Age": 22,
                              "Team(s)": "MEM",
                              "Pos": "C",
                              "G": 37,
                              "MP": 772,
                              "Off": "−0.3",
                              "Def": "+1.4",
                              "Tot": "+1.1",
                              "WAR": 1.6,
                              "WAR/82": 2.6
                            },
                            {
                              "Rank": 132,
                              "": "",
                              "Player": "Nikola Jović",
                              "Age": 21,
                              "Team(s)": "MIA",
                              "Pos": "PF",
                              "G": 41,
                              "MP": "1,025",
                              "Off": "+0.2",
                              "Def": "+0.1",
                              "Tot": "+0.3",
                              "WAR": 1.6,
                              "WAR/82": 2.6
                            },
                            {
                              "Rank": 133,
                              "": "",
                              "Player": "Dean Wade",
                              "Age": 28,
                              "Team(s)": "CLE",
                              "Pos": "PF",
                              "G": 35,
                              "MP": 799,
                              "Off": "−1.1",
                              "Def": "+2.0",
                              "Tot": "+0.9",
                              "WAR": 1.6,
                              "WAR/82": 2.5
                            },
                            {
                              "Rank": 134,
                              "": "",
                              "Player": "Onyeka Okongwu",
                              "Age": 24,
                              "Team(s)": "ATL",
                              "Pos": "C",
                              "G": 45,
                              "MP": "1,130",
                              "Off": "+0.5",
                              "Def": "−0.5",
                              "Tot": "−0.0",
                              "WAR": 1.6,
                              "WAR/82": 2.5
                            },
                            {
                              "Rank": 135,
                              "": "",
                              "Player": "Gary Trent Jr.",
                              "Age": 26,
                              "Team(s)": "MIL",
                              "Pos": "SG",
                              "G": 45,
                              "MP": "1,113",
                              "Off": "−0.1",
                              "Def": "+0.1",
                              "Tot": "−0.0",
                              "WAR": 1.5,
                              "WAR/82": 2.5
                            },
                            {
                              "Rank": 136,
                              "": "",
                              "Player": "Paul Reed",
                              "Age": 25,
                              "Team(s)": "DET",
                              "Pos": "C",
                              "G": 29,
                              "MP": 286,
                              "Off": "+1.3",
                              "Def": "+5.5",
                              "Tot": "+6.8",
                              "WAR": 1.5,
                              "WAR/82": 2.4
                            },
                            {
                              "Rank": 137,
                              "": "",
                              "Player": "Lonzo Ball",
                              "Age": 27,
                              "Team(s)": "CHI",
                              "Pos": "PG",
                              "G": 30,
                              "MP": 647,
                              "Off": "−1.1",
                              "Def": "+2.7",
                              "Tot": "+1.6",
                              "WAR": 1.5,
                              "WAR/82": 2.4
                            },
                            {
                              "Rank": 138,
                              "": "",
                              "Player": "Miles McBride",
                              "Age": 24,
                              "Team(s)": "NYK",
                              "Pos": "PG",
                              "G": 41,
                              "MP": 954,
                              "Off": "+0.5",
                              "Def": "−0.2",
                              "Tot": "+0.3",
                              "WAR": 1.5,
                              "WAR/82": 2.4
                            },
                            {
                              "Rank": 139,
                              "": "",
                              "Player": "Kris Dunn",
                              "Age": 30,
                              "Team(s)": "LAC",
                              "Pos": "PG",
                              "G": 44,
                              "MP": 991,
                              "Off": "−2.8",
                              "Def": "+3.0",
                              "Tot": "+0.2",
                              "WAR": 1.5,
                              "WAR/82": 2.4
                            },
                            {
                              "Rank": 140,
                              "": "",
                              "Player": "De'Andre Hunter",
                              "Age": 27,
                              "Team(s)": "ATL",
                              "Pos": "SF",
                              "G": 37,
                              "MP": "1,064",
                              "Off": "+1.5",
                              "Def": "−1.5",
                              "Tot": "−0.0",
                              "WAR": 1.5,
                              "WAR/82": 2.3
                            }
                          
                      
                  
              

  ]

  export default rapport_ranking;